### ISSUE TITLE
Interval doesn't respect -1

### ISSUE THREAD

**Issue by smellyonionman** [greeves12/BugManager#3]
I'm not able to suppress the reminder text by using -1; 0 has not worked either.
So right now it's set to 99999, but -1 would always be nicer.

It would also be great to be able to localize the prefix text so it isn't always "&d[Bug&bManager]".
Update:  It isn't respecting 99999, either.

**Comment by greeves12** [comment]
Hi, thanks for contacting me about your issue. Could you please post any console errors regarding bug manager, config and version of your server as well as the version of bug manager. 

If you decompile the plugin you can change the prefix.
